export enum IncidentType {
  FIRE = 'FIRE',
  MEDICAL = 'MEDICAL',
  ACCIDENT = 'ACCIDENT',
  OTHER = 'OTHER'
}

export enum IncidentStatus {
  PENDING = 'PENDING',       // รอรับแจ้ง
  IN_PROGRESS = 'IN_PROGRESS', // กำลังดำเนินการ
  CLOSED = 'CLOSED'          // ปิดงาน
}

export interface Incident {
  id: string;
  type: IncidentType;
  reporterName: string;
  reporterPhone: string;
  description: string;
  image?: string; // Base64 data URI
  location: {
    lat: number;
    lng: number;
    address?: string;
  };
  status: IncidentStatus;
  timestamp: number;
  aiSummary?: string; // Generated by Gemini
  officerNotes?: string;
}

export interface DashboardStats {
  total: number;
  pending: number;
  active: number;
  closed: number;
}